### ISSUE TITLE
Fix DRY issues in CSS

### ISSUE THREAD

**Issue by chloetruax** [cviacrucis/Projects#3]
Any time you're using a declaration like `display: flex;` multiple times throughout the CSS you want to probably split that out into a helper class:
``` CSS
    .flex{
        display: flex;
    }
```

And then add it to the appropriate HTML elements.
